/*
 * Waiting List Api
 *
 * Consulting List management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xtodorovic@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package consulting

import (
	"github.com/gin-gonic/gin"
)

type ConsultationsAPI interface {


    // DeleteConsultation Delete /api/consultation-form/:requestId/delete
    // Delete consultation 
     DeleteConsultation(c *gin.Context)

    // GetRequestsListEntries Get /api/requests-list/:requestId/entries
    // Provides the requests list 
     GetRequestsListEntries(c *gin.Context)

    // SubmitConsultingForm Post /api/consulting-form
    // Submit a new consultation request 
     SubmitConsultingForm(c *gin.Context)

    // UpdateConsultation Patch /api/consultation-form/:requestId
    // Update consultation with time and video link 
     UpdateConsultation(c *gin.Context)

}