apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

configMapGenerator:
  - name: mt-consulting-webapi-mongodb-init
    files:
      - params/init-db.js
  - name: mt-consulting-webapi-config
    literals:
      - database=mt-consulting
      - collection=consulting
patches:
- path: patches/webapi.deployment.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: mt-consulting-webapi