openapi: 3.0.0
servers:
  - description: Cluster Endpoint
    url: /api

info:
  title: Consulting Form API
  description: Handles submission of consultation forms
  version: "1.0.0"
  contact:
    email: xtodorovic@stuba.sk
  license:
    name: CC BY 4.0
    url: "https://creativecommons.org/licenses/by/4.0/"

tags:
  - name: consultingForm
    description: Consulting Form submission API

paths:
  /consulting-form:
    post:
      tags:
        - consultingForm
      summary: Submit a new consultation request
      operationId: submitConsultingForm
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConsultingForm'
            examples:
              sample:
                value:
                  name: John Doe
                  email: john@example.com
                  symptoms: Fatigue and nausea
      responses:
        "201":
          description: Consultation request successfully submitted
        "400":
          description: Invalid input

components:
  schemas:
    ConsultingForm:
      type: object
      required:
        - name
        - email
        - symptoms
      properties:
        name:
          type: string
          example: John Doe
        email:
          type: string
          format: email
          example: john@example.com
        symptoms:
          type: string
          example: Persistent headache and dizziness
